/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminCadastroRouteImport } from './routes/admin.cadastro'
import { Route as JogoGameIdRouteImport } from './routes/jogo.$gameId'
import { Route as AdminEditarGameIdRouteImport } from './routes/admin.editar.$gameId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCadastroRoute = AdminCadastroRouteImport.update({
  id: '/admin/cadastro',
  path: '/admin/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const JogoGameIdRoute = JogoGameIdRouteImport.update({
  id: '/jogo/$gameId',
  path: '/jogo/$gameId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEditarGameIdRoute = AdminEditarGameIdRouteImport.update({
  id: '/admin/editar/$gameId',
  path: '/admin/editar/$gameId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/cadastro': typeof AdminCadastroRoute
  '/jogo/$gameId': typeof JogoGameIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/editar/$gameId': typeof AdminEditarGameIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/cadastro': typeof AdminCadastroRoute
  '/jogo/$gameId': typeof JogoGameIdRoute
  '/admin': typeof AdminIndexRoute
  '/admin/editar/$gameId': typeof AdminEditarGameIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/cadastro': typeof AdminCadastroRoute
  '/jogo/$gameId': typeof JogoGameIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/editar/$gameId': typeof AdminEditarGameIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin/cadastro'
    | '/jogo/$gameId'
    | '/admin/'
    | '/admin/editar/$gameId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin/cadastro'
    | '/jogo/$gameId'
    | '/admin'
    | '/admin/editar/$gameId'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/admin/cadastro'
    | '/jogo/$gameId'
    | '/admin/'
    | '/admin/editar/$gameId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  AdminCadastroRoute: typeof AdminCadastroRoute
  JogoGameIdRoute: typeof JogoGameIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminEditarGameIdRoute: typeof AdminEditarGameIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/cadastro': {
      id: '/admin/cadastro'
      path: '/admin/cadastro'
      fullPath: '/admin/cadastro'
      preLoaderRoute: typeof AdminCadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jogo/$gameId': {
      id: '/jogo/$gameId'
      path: '/jogo/$gameId'
      fullPath: '/jogo/$gameId'
      preLoaderRoute: typeof JogoGameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/editar/$gameId': {
      id: '/admin/editar/$gameId'
      path: '/admin/editar/$gameId'
      fullPath: '/admin/editar/$gameId'
      preLoaderRoute: typeof AdminEditarGameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  AdminCadastroRoute: AdminCadastroRoute,
  JogoGameIdRoute: JogoGameIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminEditarGameIdRoute: AdminEditarGameIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
